### ISSUE TITLE
生成dockerfile时报错 nb_cli_plugin_docker/handler.py", line 203, in get_driver_type

### ISSUE THREAD

**Issue by dev-soragoto** [nonebot/cli-plugin-docker#15]
```bash
[soragoto@soragoto-pc simple-bot]$ nb docker generate
Using python: /home/soragoto/simple-bot/.venv/bin/python
Traceback (most recent call last):
  File "/home/soragoto/.local/bin/nb", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli/__main__.py", line 10, in main
    anyio.run(cli_main, *args)
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_core/_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2034, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2022, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli/__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli/cli/utils.py", line 63, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli/cli/utils.py", line 71, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/from_thread.py", line 58, in run
    return async_backend.run_async_from_thread(func, args, token=token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2217, in run_async_from_thread
    return f.result()
           ^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2204, in task_wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli_plugin_docker/cli.py", line 76, in generate
    is_reverse = await get_driver_type(python_path=python_path, cwd=cwd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli/handlers/meta.py", line 134, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli/handlers/meta.py", line 183, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/share/pipx/venvs/nb-cli/lib/python3.12/site-packages/nb_cli_plugin_docker/handler.py", line 203, in get_driver_type
    return json.loads(stdout.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

查看代码段发现
```python
async def get_driver_type(
    adapters: Optional[List[SimpleInfo]] = None,
    builtin_plugins: Optional[List[str]] = None,
    python_path: Optional[str] = None,
    cwd: Optional[Path] = None,
) -> bool:
    bot_config = get_nonebot_config()
    if adapters is None:
        adapters = bot_config.adapters
    if builtin_plugins is None:
        builtin_plugins = bot_config.builtin_plugins
    if python_path is None:
        python_path = await get_default_python()
    if cwd is None:
        cwd = get_project_root()

    t = templates.get_template("docker/get_driver_type.py.jinja")
    proc = await asyncio.create_subprocess_exec(
        python_path,
        "-W",
        "ignore",
        "-c",
        await t.render_async(adapters=adapters, builtin_plugins=builtin_plugins),
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    if proc.returncode != 0:
        raise GetDriverTypeError(stderr)

    return json.loads(stdout.strip())
```
其中`stdout.strip()`似乎并不是json 直接print输出
```bash
b'Shell: 140006255591392 \xe8\xbf\x9e\xe6\x8e\xa5\nfalse'
```
想询问一下有没有debug思路

**Comment by yanyongyu** [comment]
你是否使用的是windows？如果是，应该是你的shell配置了启动时执行某些代码，请检查你的注册表。

**Comment by dev-soragoto** [comment]
> 你是否使用的是windows？如果是，应该是你的shell配置了启动时执行某些代码，请检查你的注册表。

是arch on wsl2，我后面也怀疑可能是wsl的问题，所以我在一台debian12服务器上尝试生成dockerfile

结果比较相似
```bash
(simple-bot) soragoto@racknerd-3ae4b07:~/simple-bot$ nb docker generate
Using python: /home/soragoto/simple-bot/.venv/bin/python
Traceback (most recent call last):
  File "/home/soragoto/.local/bin/nb", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli/__main__.py", line 10, in main
    anyio.run(cli_main, *args)
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2034, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2022, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli/__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli/cli/utils.py", line 63, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli/cli/utils.py", line 71, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/from_thread.py", line 58, in run
    return async_backend.run_async_from_thread(func, args, token=token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2217, in run_async_from_thread
    return f.result()
           ^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2204, in task_wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli_plugin_docker/cli.py", line 76, in generate
    is_reverse = await get_driver_type(python_path=python_path, cwd=cwd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli/handlers/meta.py", line 134, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli/handlers/meta.py", line 183, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soragoto/.local/pipx/venvs/nb-cli/lib/python3.11/site-packages/nb_cli_plugin_docker/handler.py", line 203, in get_driver_type
    return json.loads(stdout.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by yanyongyu** [comment]
输出里明显产生了不应该输出的内容，请检查你的shell启动脚本是否有额外输出内容，例如你在打开shell的时候是否有前置输出内容。

**Comment by dev-soragoto** [comment]
> 输出里明显产生了不应该输出的内容，请检查你的shell启动脚本是否有额外输出内容，例如你在打开shell的时候是否有前置输出内容。

这个方法的预期输出应该是什么呢

**Comment by yanyongyu** [comment]
只有false那一行，前面那一行不是nb输出的内容

**Comment by dev-soragoto** [comment]
> > 只有false那一行，前面那一行不是nb输出的内容
> 
> 好的谢谢，我再想办法排查一下

虽然我没有查出来究竟为什么会这样，不过我把方法返回值直接改成false暂时先用了下去，issue我就先关掉了 谢谢你的帮助
